### ISSUE TITLE
how do you set api keys?

### ISSUE THREAD

**Issue by amirri** [alpkeskin/mosint#54]
please someone let me know, and also when i look up the social media accounts all i see is 👀(eye emoji) it doesnt tell me social names.

**Comment by LetsSeeHowThisGoes** [comment]
Having that issue myself. I looked up how to set the api Keys since I kept getting "The syntax of the command is incorrect." regardless if I was in the mosint directory. I used [this](https://help.openai.com/en/articles/5112595-best-practices-for-api-key-safety) to set up the api keys as environmental so when I'm in the mosint directory I can enter, for example, "set hunter" and get "hunter=<hunter.io API key>". I think I've done something wrong since I get the same results regardless of if I set the keys.

**Comment by alpkeskin** [comment]
Mosint cannot access social media names, it only checks if the target email has an account on that social media app.
